BackEnd/BackArendaSchmot/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url
from firstapp import views


urlpatterns = [
    path('tovars/<int:Str>/', views.FindTovars),
    path('tovars/', views.FindTovars),
    path('tovar/<int:id>/', views.tovars),
    path('tovar/', views.tovars),
    path('sets/', views.Setssss),
    path('set/<int:id>/', views.SetOne),
    path('auto/', views.auto),
    path('kabinet/',views.kabinet),
    path('Edit/', views.edit),
    path('Editpass/', views.editPass),
    path('calend/', views.calend),
    path('history/',views.HistOper),
    path('korzina/', views.Korz),
    path('Otz/<int:id>/', views.tovarAddOT),
    path('zakaz/<int:id>/', views.ZakazClient),
    path('Registration/', views.Registr),
    path('Vihod/', views.Vihod),
    path('main/', views.main),
    path('/', views.main),


    path('admtovars/', views.AdmTovar),
    path('admtovar/<int:id>', views.AdmKardTovar),
    path('admaddsize/<int:id>', views.AdmAddSize),
    path('admedittov/', views.AdmEdTov),
    path('admnalichie/<int:id>', views.NalichieTovar),
    path('admnenalichie/<int:id>', views.NenalichieTovar),
    path('admntovaredit/<int:id>', views.EditTov),
    path('admntovarphoto/<int:id>', views.EditTovPhoto),
    path('admnpersons/', views.GetPerson),
    path('admnkardperson/<int:id>', views.AdmMaxPerson),
    path('admeditperson/<int:id>', views.AdmEditPerson),
    path('admnotzivi/', views.AdminspisokOtz),
    path('admnotziv/<int:id>', views.AdmOtz),
    path('admaddotz/<int:id>', views.AdmAddOtz),
    path('admeditotz/<int:id>', views.AdmEditOtz),
    path('admpaid/', views.AdmPaid),
    path('admjournal/', views.GetJournal),
    path('editadmjournal/<int:id>', views.EditJournal),
    path('admzakaz/<int:id>', views.zakaz),
    path('admtovarszakaz/<int:id>', views.TovarZakaz),
    path('admzakazi/',views.GetZakazi),
    path('admpaid/<int:id>',views.GetPaid)

]

BackEnd/firstapp/models.py
from django.db import models
from django.db.models import Q
from django.forms import ModelForm,Textarea,Select, SelectDateWidget,DateTimeInput, inlineformset_factory, CheckboxInput, FileInput, NumberInput
from django.contrib.auth.models import User
from datetime import timedelta, datetime, date




class Brand (models.Model):
    name = models.CharField(db_index=True,max_length=100)
    def __str__(self):
        return u'{0}'.format(self.name)

class TypeTovars (models.Model):
    name = models.TextField(db_index=True)
    def __str__(self):
        return u'{0}'.format(self.name)

class Sex (models.Model):
    name = models.TextField()
    def __str__(self):
        return u'{0}'.format(self.name)

class Tovar (models.Model):
    name = models.CharField(db_index=True,max_length=100)
    Opisanie = models.TextField()
    brand = models.ForeignKey(Brand,on_delete=models.SET_NULL, null=True)
    DateAdd = models.DateTimeField()
    DateEdit = models.DateTimeField()
    Sex = models.ForeignKey(Sex, on_delete=models.SET_NULL, null=True)
    Material = models.TextField(null=True)
    Del = models.BooleanField()
    def __str__(self):
        return u'{0}'.format(self.name)

class Set(models.Model):
    name = models.CharField(db_index=True,max_length=100)
    text = models.TextField()
    DateAdd = models.DateTimeField()
    DateEdit = models.DateTimeField()
    Sex = models.BooleanField(null=True)

class TovarTypeTovar(models.Model):
    tovar = models.ForeignKey(Tovar, on_delete=models.CASCADE)
    typpe = models.ForeignKey(TypeTovars, on_delete=models.CASCADE)



class VidArendi (models.Model):
    name = models.CharField(max_length=50)
    vikup = models.BooleanField()
    opisanie = models.TextField()
    def __str__(self):
        return u'{0}'.format(self.name)

class Person(models.Model):
    user = models.OneToOneField(User,on_delete = models.CASCADE, null=True)
    sex = models.BooleanField(null=True)
    phone = models.IntegerField(null=True)
    Vk = models.TextField(null=True);
    Insta = models.TextField(null=True);
    Status = models.CharField(max_length=20,null=True)
    DateReg = models.DateField(null=True);
    DataLast = models.DateTimeField(null=True);
    Zamoroz = models.BooleanField(null=True);
    Email = models.TextField(null=True)
    name = models.CharField(db_index=True,max_length=300)
    PhotoPerson = models.TextField(null=True)
    Bird = models.DateField(null=True)
    Adress = models.TextField(null=True)
    balance = models.FloatField(null=True)

    class Meta:
        unique_together = ( 'Email',)

    objects = models.Manager()
    def __str__(self):
        return u'{0}'.format(self.name)

class Manager(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, null=True)
    DateReg = models.DateField(null=True);
    DataLast = models.DateTimeField(null=True);
    name = models.TextField()
    email = models.TextField()
    phone = models.TextField()

class VidArendiTovars (models.Model):
    set = models.ForeignKey(Set,on_delete = models.CASCADE, null=True)
    tovar = models.ForeignKey(Tovar,on_delete = models.CASCADE, null= True)
    vidArendi = models.ForeignKey(VidArendi, on_delete=models.CASCADE)
    stoimost = models.FloatField();
    vikup = models.IntegerField(null=True);
    Vozvrat = models.IntegerField();
    platej = models.IntegerField();
    def __str__(self):
        return u'{0}'.format(self.vidArendi.name)



class PhotoTovara (models.Model):
    photo = models.FileField()
    tovar = models.ForeignKey(Tovar,on_delete = models.CASCADE, null=True)
    set = models.ForeignKey(Set, on_delete= models.CASCADE, null=True)
    main = models.BooleanField(null=True)
    delete = models.BooleanField()


class TovarsSets(models.Model):
    set = models.ForeignKey(Set, on_delete=models.CASCADE)
    tovars = models.ForeignKey(Tovar, on_delete=models.CASCADE)
    skidka = models.FloatField()


class LikePerson(models.Model):
    person = models.ForeignKey(Person, on_delete=models.CASCADE)
    tovar = models.ForeignKey(Tovar, on_delete=models.SET_NULL, null=True)
    sets = models.ForeignKey(Set, on_delete=models.SET_NULL, null=True)


class Otziv (models.Model):
    Opisanie = models.TextField(db_index=True)
    zvezdi = models.IntegerField()
    Person = models.ForeignKey(Person, on_delete=models.CASCADE, null=True)
    Tovar = models.ForeignKey(Tovar, on_delete=models.CASCADE, null=True)
    date = models.DateTimeField(null=True)
    Set = models.ForeignKey(Set, on_delete=models.CASCADE, null=True)
    Status = models.TextField()
    delete = models.BooleanField(null=True)
    Otvet = models.TextField(null=True)
    nameperson = models.TextField(null=True)


class Size(models.Model):
    name = models.TextField()
    def __str__(self):
        return u'{0}'.format(self.name)


class SizeTovars(models.Model):
    Size = models.ForeignKey(Size, on_delete=models.SET_NULL, null=True)
    Tovar = models.ForeignKey(Tovar,on_delete = models.CASCADE, null=True)
    set = models.ForeignKey(Set, on_delete=models.CASCADE, null=True)
    nalichie = models.BooleanField()

    def __str__(self):
        return u'{0}'.format(self.Size.name)

class TovarPerson(models.Model):
    VidArendiTovars = models.ForeignKey(VidArendiTovars, on_delete=models.CASCADE)
    person = models.ForeignKey(Person,on_delete=models.CASCADE)
    Data = models.DateTimeField();
    size = models.TextField();

class AddTovars(models.Model):
    date = models.DateTimeField()
    client = models.ForeignKey(Person, on_delete=models.SET_NULL, null=True)
    tovar = models.ForeignKey(Tovar, on_delete=models.SET_NULL, null=True)
    size = models.ForeignKey(SizeTovars, on_delete=models.SET_NULL, null=True)
    count = models.IntegerField()
    PlusMinus = models.BooleanField()

class AddPaid(models.Model):
    status = models.BooleanField()
    plusminus = models.BooleanField()
    person = models.ForeignKey(Person, on_delete = models.CASCADE)
    date = models.DateTimeField()
    money = models.FloatField()
    tovPer = models.ForeignKey(TovarPerson, on_delete=models.SET_NULL, null=True)


class Seaz(models.Model):
    name = models.TextField()


class SezonTovar(models.Model):
    seaz = models.ForeignKey(Seaz,on_delete = models.CASCADE, null=True)
    tovar = models.ForeignKey(Tovar, on_delete=models.CASCADE, null=True)
    set = models.ForeignKey(Set, on_delete=models.CASCADE, null=True)

class Korzina(models.Model):
    person = models.ForeignKey(Person, on_delete=models.CASCADE)

class TovarsKorzine(models.Model):
    tovar = models.ForeignKey(VidArendiTovars, on_delete=models.CASCADE)
    korzina = models.ForeignKey(Korzina, on_delete=models.CASCADE)

class Zakaz(models.Model):
    status = models.BooleanField()
    nomer = models.TextField()
    date = models.DateTimeField()
    person = models.ForeignKey(Person, on_delete=models.CASCADE)
    vidann = models.BooleanField()

    class Meta:
        unique_together = ('nomer',)

class TovarsZakaz(models.Model):
    zakaz = models.ForeignKey(Zakaz, on_delete=models.CASCADE)
    tovar = models.ForeignKey(VidArendiTovars, on_delete=models.CASCADE)
    size = models.ForeignKey(SizeTovars, on_delete=models.CASCADE)

class Vidacha(models.Model):
    client = models.ForeignKey(Person, on_delete=models.CASCADE)
    date = models.DateTimeField()
    manager = models.ForeignKey(Manager, on_delete=models.CASCADE)
    status = models.BooleanField()
    comment = models.TextField(null=True)
    zakaz = models.ForeignKey(Zakaz, on_delete=models.CASCADE)

class AddVidachaForm(ModelForm):
    class Meta:
        model = Vidacha
        fields = ['client','date','manager','status','comment','zakaz']

class ZakaForm(ModelForm):
    class Meta:
        model = Zakaz
        fields = ['date','person']


class OtzForm(ModelForm):
    class Meta:
        model = Otziv
        fields = ['Opisanie', 'zvezdi', 'date', 'nameperson','Tovar','Status']
        widgets = {
            'nameperson': Textarea(attrs={'cols': 80, 'rows': 1}),
            'zvezdi': Select(choices=((1,'1 звезда'),(2,'2 звезды'),(3,'3 звезды'),(4,'4 звезды'),(5,'5 звезд'))),
            'date': SelectDateWidget(years=range(datetime.today().year-50,datetime.today().year+50)),
        }

class EditOtzForm(ModelForm):
    class Meta:
        model = Otziv
        fields = ['Opisanie', 'zvezdi', 'date','Tovar','Status']
        widgets = {
            'zvezdi': Select(choices=((1,'1 звезда'),(2,'2 звезды'),(3,'3 звезды'),(4,'4 звезды'),(5,'5 звезд'))),
            'date': SelectDateWidget(years=range(datetime.today().year-50,datetime.today().year+50)),
        }

class PersonForm(ModelForm):
    class Meta:
        model = Person
        fields = ['sex','phone','Email','name','Bird','Adress']

class SizeForm(ModelForm):

    def __init__(self,idd, *args, **kwargs):
        super(SizeForm, self).__init__(*args, **kwargs)
        size = []

        if idd != None:
            tovar = Tovar.objects.filter(id=idd)
            if len(tovar)>0:
                sizetovar = tovar[0].sizetovars_set.all()
            self.fields['size'].queryset = tovar[0].sizetovars_set.all()

    class Meta:
        model = AddTovars
        fields = ['count','size','tovar','date', 'client','PlusMinus']
        widgets = {
            'date':DateTimeInput(attrs={'id': 'datepicker'}),
        }

class AddSizeTov(ModelForm):

    def __init__(self,idd, *args, **kwargs):
        super(AddSizeTov, self).__init__(*args, **kwargs)
        size = []

        if idd != None:
            tovar = Tovar.objects.filter(id=idd)
            if len(tovar)>0:
                sizetovar = tovar[0].sizetovars_set.all()
                for t in sizetovar:
                    size.append(t.Size.name)
            self.fields['Size'].queryset = Size.objects.filter(~Q(name__in=size))

    class Meta:
        model = SizeTovars
        fields = ['Size','Tovar','nalichie']


class AddArendaTovars(ModelForm):

BackEnd/templates/Autorization_V2.html
{% extends "base.html" %}

{% load staticfiles %}

{% block title %}
<title> Авторизация </title>
{% endblock %}

{% block content %}


<div class="Base__flex Bread-flex">
    <div class="Bread">
        <a href="/main/" class="Base__txt-kelson Bread__txt">
            Главная
        </a>
    </div>
    <div class="Bread-poloska"></div>
    <div class="Bread Bread_viible_orange">
        <div class="Base__txt-kelson Bread__txt">
            Авторизация
        </div>
    </div>
</div>

<div style="margin-bottom:2em;">

<div class=" Page__element-oba">
    <div class="Page__element-obertka">
        <div class="zagolovok Page__zagolovok Page__zagolovok-funny Page__element-zagolovok">Авторизация</div>
    </div>
    <div class="Autoriz ">
    <form method="post" action="/auto/">
        <div class=" Base__flex Autoriz__flex">
            <div class="Base__flex Base__flex_type_column Autoriz__Base-column  Autoriz__txt-main">
                <div class="Base__txt-kelson Autoriz__column-element Autoriz__txt">Логин</div>
                <div class="Base__txt-kelson Autoriz__column-element Autoriz__txt">Пароль</div>
            </div>

            <div class="Base__flex Base__flex_type_column Autoriz__Base-column Autoriz-LEFT">
                <input  type="text" name="login" placeholder="dimon228"   id="login" class="Autoriz__column-element Autoriz__input">
                <input  type="password" name="password" placeholder="NeOtgadaesh"  id="password" class="Autoriz__column-element Autoriz__input">
            </div>
            <button type="submit" class="Base__button Base__button_color_orange Page__button Autoriz__flex-el">Отправить</button>
        </div>
        {% csrf_token %}
    </form>
	<div style="margin-top:1em; display:flex; justify-content:center;">
		<a href="/Registration/"> Регистрация </a>
	</div>
    </div>
</div>
</div>

{% endblock %}

{% block style %}
<link rel="stylesheet" type="text/css" href="{% static "Main/style/Main.css"%}"/ >
<link rel="stylesheet" type="text/css" href="{% static "Autoriz/style/Autoriz.css"%}"/ >
<link rel="stylesheet" type="text/css" href="{% static "bread/style/bread.css"%}"/ >
{% endblock %}

BackEnd/templates/Bot_Card-Otz.html
{% extends "Bot_base.html" %}
{% load staticfiles %}
{% load widget_tweaks %}


{% block title %}

<title> Карточка отзыва</title>

{% endblock %}

{% block main %}

<div class="container mt-3 mb-3">

    <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="">Главная</a></li>
            <li class="breadcrumb-item"><a href="/admnotzivi/">Список отзывов</a></li>
            <li class="breadcrumb-item active" aria-current="page">Отзыв: {otziv.zvezdi}} звезды </li>
        </ol>
    </nav>

    <h1 class="mb-3 text-center">Отзыв</h1>

    <div class="row">
        <div class="col">
            <div class="card" >
                
                <div class="card-body">
                     <h5 class="card-title">Отзыв {{otziv.zvezdi}} звезды</h5>
                        <h6 class="card-subtitle mb-2 text-muted">Дата: {{otziv.date}}</h6>
                    <p class="card-text">{{otziv.Opisanie}}</p>
					{% if otziv.delete %}
					<h6 class="card-subtitle mb-2">Отзыв удален</h6>
					{% else %}
					<h6 class="card-subtitle mb-2">Отзыв не удален</h6>
					{% endif %}
					<form method="POST" action="/admnotziv/{{otziv.id}}">
						{% csrf_token %}
						<input type="hidden" name="Delete" id="itogo" value="1">
						<button type="sumbit" class="btn btn-danger m-1">Удалить</button>
					</form>
					<form method="POST" action="/admnotziv/{{otziv.id}}">
						{% csrf_token %}
						<input type="hidden" name="Delete" id="itogo" value="0">
						<button type="sumbit" class="btn btn-danger m-1">Восстановить</button>
					</form>
                    <a href="/admeditotz/{{otziv.id}}" class="btn btn-secondary m-1">Редактировать</a>
                </div>
                <ul class="list-group list-group-flush">
                    <li class="list-group-item"><h5>Статус: {{otziv.Status}}</h5>
					<form method="POST" action="/admnotziv/{{otziv.id}}">
						{% csrf_token %}
						<input type="hidden" name="Razresh" value="1">
						<button id="okay"  class="btn btn-success m-1">Разрешить</button>
					</form>
					<form method="POST" action="/admnotziv/{{otziv.id}}">
						{% csrf_token %}
						<input type="hidden" name="Razresh" value="0">
						<button class="btn btn-secondary m-1">Отклонить</button>
					</form>
                    </li>

                    <li class="list-group-item"><h5>Клиент: {{client.name}}</h5>
                        <a href="/admnkardperson/{{client.id}}" class="btn btn-secondary m-1">Перейти к клиенту</a>
                    </li>
                    <li class="list-group-item"><h5>Товар отзыва</h5>
                        <a href="/admtovar/{{tovar.id}}" class="list-group-item list-group-item-action flex-column align-items-start border border-dark">

                            <div class="d-flex w-100 justify-content-start">
                                <h5 class="mb-1 mr-2">Название: </h5>
								<p class="mb-1">{{tovar.name}}</p>
                            </div>
							
							<div class="d-flex w-100 justify-content-start">
                                <h5 class="mb-1 mr-2">Описание: </h5>
								<p class="mb-1">{{tovar.opisanie}}</p>
                            </div>
							
							<div class="d-flex w-100 justify-content-start">
                                <h5 class="mb-1 mr-2">Бренд: </h5>
								<p class="mb-1">{{tovar.brand}}</p>
                            </div>
							
							<div class="d-flex w-100 justify-content-start">
                                <h5 class="mb-1 mr-2">Пол: </h5>
								<p class="mb-1">{{tovar.sex}}</p>
                            </div>
							
							<div class="d-flex w-100 justify-content-start">
                                <h5 class="mb-1 mr-2">Материал: </h5>
								<p class="mb-1">{{tovar.Material}}</p>
                            </div>
							
							<div class="d-flex w-100 justify-content-start">
                                <h5 class="mb-1 mr-2">Тип: </h5>
								<p class="mb-1">{{tovar.del}}</p>
                            </div>
							
							<div class="d-flex w-100 justify-content-start">
                                <h5 class="mb-1 mr-2">Размеры: </h5>
								{% for si in tovar.size %}
								<p class="mb-1 mr-2">{{si.Size__name}} <span class="badge badge-secondary"> Наличие: </span> <span class="badge badge-secondary"> {{si.nalichie}}</span></p>
								{% endfor %}
                            </div>
							
							 <div class="d-flex w-100 justify-content-start">
                                <h5 class="mb-1 mr-2">аренда: </h5>
								{% for ar in tovar.arenda %}
								<p class="mb-1 mr-2">{{ar.vidArendi__name}} </p>
								{% endfor %}
                            </div>
							
                             <a href="/admtovar/{{tovar.id}}" class="btn btn-secondary m-1 mt-2">Перейти к товару</a>
                        </a>
                    </li>
                    <li class="list-group-item"><h5>Ответить отзыву</h5>
					
					{% if otziv.otvet != None %}
					<h6 class="card-subtitle mt-3 ">Ответ отзыву</h6>
					<p class="card-text">{{otziv.otvet}}</p>
					{% else %}
					<h6 class="card-subtitle mb-2">Нет ответа</h6>
					{% endif %}
                        <form method="POST" action="/admnotziv/{{otziv.id}}">
						{% csrf_token %}
                            <div class="form-group">
                                <label for="exampleFormControlTextarea1">Ответ отзыву</label>
                                <textarea class="form-control" id="exampleFormControlTextarea1" name="textotvet" rows="3"></textarea>
                            </div>
                            <button class="btn btn-success"> Ответить отзыву/изменить ответ </button>

                        </form>
						<form method="POST" class="mt-2" action="/admnotziv/{{otziv.id}}">
						{% csrf_token %}
                            <input type="hidden" name="DellOtvet" value="1">
                            <button class="btn btn-danger"> Удалить ответ </button>
                        </form>
                    </li>
                </ul>

            </div>
        </div>
    </div>
</div>
{% endblock %}

BackEnd/templates/Bot_spispok-clientov.html
{% extends "Bot_base.html" %}
{% load staticfiles %}
{% load widget_tweaks %}


{% block title %}

<title> Cписок клиентов</title>

{% endblock %}

{% block main %}


    <div class="ml-3 mt-3 d-flex flex-column align-items-center">

        <nav aria-label="breadcrumb">
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="#">Главная</a></li>
                <li class="breadcrumb-item active" aria-current="page">Список Клиентов</li>
            </ol>
        </nav>

        <h1 class="mb-3">Список Клиентов</h1>

        <div class="btn-group mb-3" role="group" aria-label="Basic example">
            <a href="#collapseFilter" class="btn btn-primary" data-toggle="collapse"> <i class="fas fa-keyboard mr-1"></i> Фильтр</a>
        </div>
		
		
				<form method="GET" action="/admnpersons">
				<div class="d-flex bg-white border mb-4 p-2 justify-content-center align-items-center">
					
					<div class="form-group ml-2 mr-2">
                        <label for="id_str" >Текущая страница: {{zapros.str}}</label>
                    
						<div class='btn-spn btn-spn-lg input-group'>
						  <span class='input-group-btn'>
							<button
							  class='btn btn-secondary btn-spn-down' 
							  type='button'><i class="fa fa-minus"></i></button>
						  </span> 
						  {{formsort.str|add_class:"btn-spn-input form-control text-center"}}
						  <span class='input-group-btn'>
							<button        
							  class='btn btn-secondary btn-spn-up'
							  type='button'><i class="fa fa-plus"></i></button>
						  </span>
						</div>
					</div>
					
					<div class="form-group ml-2 mr-2">
                        <label for="id_kolich" >Текущее количество: {{zapros.kolich}}</label>
                    
						<div class='btn-spn btn-spn-lg input-group'>
						  <span class='input-group-btn'>
							<button
							  class='btn btn-secondary btn-spn-down' 
							  type='button'><i class="fa fa-minus"></i></button>
						  </span> 
						  {{formsort.kolich|add_class:"btn-spn-input form-control text-center"}}
						  <span class='input-group-btn'>
							<button        
							  class='btn btn-secondary btn-spn-up'
							  type='button'><i class="fa fa-plus"></i></button>
						  </span>
						</div>
					</div>
					
					
                    <div class="form-group ml-2 mr-2">
                        <label for="id_sort" >Текущее поле для сортировки: {{zapros.sort}}</label>
                        {{formsort.sort|add_class:"form-control"}}
                    </div>
					
                    <div class="custom-control ml-2 mr-2 custom-switch">
                        {{formsort.sortingType|add_class:"custom-control-input"}}
						 <label class="custom-control-label" for="id_sortingType">По возрастанию/убыванию</label>
                    </div>

 
                    <div class="d-flex ml-1 flex-column">
                        <button type="submit" class="btn btn-primary mt-1 mb-1">Применить</button>
                    </div>
				</div>
              
		
		
        <div class="container">

        <div class="row justify-content-center">

            <div class="col-xl-5 col-lg-5  " >

            <div class="mb-4 border p-3 border border-dark bg-white">
               
                    <div class="form-group">
                        <label for="id_name">Имя</label>
						{{mmaiinn.name|add_class:"form-control"}}
                    </div>

                    <div class="form-group">
                        <label for="id_phone">Телефон</label>
						{{mmaiinn.phone|add_class:"form-control"}}
                    </div>

                  

                    <div class="form-group">
                        <label for="exampleFormControlInput1">Баланс</label>
                        <div class="row">
                            <div class="col">
							{{mmaiinn.minprice|add_class:"form-control"}}
                            </div>
                            <div class="col">
							{{mmaiinn.maxprice|add_class:"form-control"}}
                            </div>
                        </div>
                    </div>

                    <div class="form-group">
                        <label for="exampleFormControlInput1">Число шмоток</label>
                        <div class="row">
                            <div class="col">
							{{mmaiinn.minvesh|add_class:"form-control"}}                              
                            </div>
                            <div class="col">
							{{mmaiinn.maxvesh|add_class:"form-control"}}  
                            </div>
                        </div>
                    </div>

                    <div class="form-group">
                        <label for="exampleFormControlInput1">Месячная плата</label>
                        <div class="row">
                            <div class="col">
							{{mmaiinn.monmin|add_class:"form-control"}} 
                            </div>
                            <div class="col">
							{{mmaiinn.monma|add_class:"form-control"}} 
                            </div>
                        </div>
                    </div>

                    <div class="form-group">
                        <label for="exampleFormControlInput1">Пол</label>
						<div class="custom-control custom-switch">
						{{mmaiinn.man|add_class:"custom-control-input"}}
						<label for="id_man" class="custom-control-label" >Мужской</label>
						</div>
						
						<div class="custom-control custom-switch">
						{{mmaiinn.woman|add_class:"custom-control-input"}}
						<label for="id_woman" class="custom-control-label" >Женский</label>
						</div>
                    </div>

                    <div class="form-group">
                        <label for="exampleFormControlInput1">Тип</label>
						
						<div class="custom-control custom-switch">
						{{mmaiinn.moroz|add_class:"custom-control-input"}}
							<label for="id_moroz" class="custom-control-label" >Заморожен</label>
						</div>
						
						<div class="custom-control custom-switch">
						{{mmaiinn.razmoroz|add_class:"custom-control-input"}}
							<label for="id_razmoroz" class="custom-control-label" >Разморожен</label>
						</div>
						
                    </div>

                    <div class="d-flex flex-column">
                        <button type="submit" class="btn btn-primary mt-1 mb-1">Применить</button>
                        <button type="submit" class="btn btn-info mt-1 mb-1">Сбросить</button>
                    </div>

                </form>
            </div>
            </div>


        <div class="col-xl-7 col-lg-7 ">
        <div class="list-group ">
            <a href="/Registration/" class="list-group-item list-group-item-action flex-column align-items-start bg-success border border-dark">
                <div class="d-flex w-100">
                    <h5 class="mb-1 text-uppercase text-white">Добавить клиента</h5>
                </div>
            </a>
			{% for pers in person %}
            <a href="/admnkardperson/{{pers.id}}" class="list-group-item list-group-item-action flex-column align-items-start border border-dark">
                <div class="d-flex w-100 justify-content-between">
                    <h5 class="mb-1 ml-2">{{pers.name}}</h5>
                    <small  class="mr-2">{{pers.datelast}}</small>
                </div>
                <div class="d-flex flex-wrap justify-content-between">
                    <div class="d-flex ml-2 mr-2">
                        <p class="mb-1 ">Пол: </p>
						
						{% if pers.sex == True %}
                        <p class="mb-1 ml-1">Мужской</p>
						{% else %}
						<p class="mb-1 ml-1">:Женский</p>
						{% endif %}
                    </div>
                    <div class="d-flex ml-2 mr-2">
						
                        <p class="mb-1 ">Статус: </p>
						{% if pers.zamoroz == False %}
                        <p class="mb-1 ml-1">Разморожен</p>
						{% else %}
						<p class="mb-1 ml-1">Заморожен</p>
						{% endif %}
                    </div>


                    <div class="d-flex ml-2 mr-2">
                        <p class="mb-1 ">Баланс: </p>
                        <p class="mb-1 ml-1">{{pers.balans}}</p>
                    </div>

                    <div class="d-flex ml-2 mr-2">
                        <p class="mb-1 ">Число шмоток: </p>
                        <p class="mb-1 ml-1">{{pers.schchislo}}</p>
                    </div>

                </div>
            </a>
			{% endfor %}
        </div>
        </div>
        </div>
        </div>

     
    </div>
{% endblock %}

{% block js %}
	<link rel="stylesheet" type="text/css" href="{% static "numberbootstrap/kss.css" %}"/ >
	<script src="{% static "numberbootstrap/java.js" %}"/></script>

	
{% endblock %}